### ISSUE TITLE
How to authenticate a request

### ISSUE THREAD

**Issue by anup-a** [fal-ai/lcm-websocket-demo#2]
Hi team, probably a naive question but I was not able to figure out how to authenticate a ws request. 

Things I have tried,

setting custom config
```
  fal.config({
    credentials: // combination key here
})
```

setting env variables
```
FAL_KEY_ID=
FAL_KEY_SECRET=
```

But I don't see any token being sent on request, and I see `Unauthorized` error. Thanks

**Comment by xsfa** [comment]
have you figured this out?

**Comment by chamini2** [comment]
Hey! This repo is really not being supported anymore. You can instead take a look at https://github.com/fal-ai/tldraw-fal or https://github.com/fal-ai/fal-js/blob/main/apps/demo-nextjs-app-router/app/realtime/page.tsx

Sorry about the confusion.
